# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       qca

# >> macros
# << macros

Summary:    Qt Cryptographic Architecture
Version:    2.0.3
Release:    1
Group:      System/Libraries
License:    LGPLv2+
URL:        http://delta.affinix.com/qca
Source0:    http://delta.affinix.com/download/qca/2.0/%{name}-%{version}.tar.bz2
Source100:  qca.yaml
Requires:   ca-certificates
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(QtCore) < 5
BuildRequires:  ca-certificates

%description
The Qt Cryptographic Architecture (QCA) provides a straightforward and cross-
platform API for a range of cryptographic features, including SSL/TLS,
X.509 certificates, SASL, OpenPGP, S/MIME CMS, and smart cards.


%package devel
Summary:    Qt Cryptographic Architecture - development files
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The Qt Cryptographic Architecture (QCA) provides a straightforward and cross-
platform API for a range of cryptographic features, including SSL/TLS,
X.509 certificates, SASL, OpenPGP, S/MIME CMS, and smart cards.

This package contains development files for building software that uses the
Qt Cryptographic Architecture.


%prep
%setup -q -n %{name}-%{version}/%{name}

# >> setup
# << setup

%build
# >> build pre
./configure \
--prefix=%{_prefix} \
--qtdir=%{_datadir}/qt4 \
--disable-tests \
--no-separate-debug-info \
--verbose
sed -i -e /strip/d Makefile
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc COPYING README TODO
%{_bindir}/qcatool2
%{_libdir}/libqca.so.*
%{_mandir}/*/*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/QtCrypto
%{_libdir}/libqca.prl
%{_libdir}/libqca.so
%{_libdir}/pkgconfig/qca2.pc
%{_datadir}/qt4/mkspecs/features/crypto.prf
# << files devel
